name: CI
on:
  push:
    branches:
      - port-changes

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [18, 19]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          check-latest: true
      - name: Set up React 19
        if: matrix.react == 19
        run: |
          node ./.github/workflows/patch-react19.js
          cat package.json
      - name: npm install (with legacy-peer-deps)
        run: npm i --legacy-peer-deps
      - name: Biome
        run: node --run biome:ci
      - name: Typecheck
        run: node --run typecheck
      - name: ESLint
        run: node --run eslint
      - name: Prettier
        run: node --run prettier:check
      - name: Bundle
        run: |
          node --run build
          node --run build:types
      - name: Build website
        run: node --run build:website
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: Test
        run: node --run test
        timeout-minutes: 4
      - name: Upload coverage
        if: matrix.react == 18
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/port-changes' }}
    strategy:
      matrix:
        react: [18] # Ensures publishing only runs for React 18
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: https://npm.pkg.github.com/
      - name: Set up .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "@OWNER:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
          cat ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: npm install (with legacy-peer-deps)
        run: npm i --legacy-peer-deps
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
