name: CI and Publish to GitHub Packages
on:
  push:
    branches:
      - port-changes

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [18, 19]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 23
          check-latest: true
      - name: Set up React 19
        if: matrix.react == 19
        run: |
          node ./.github/workflows/patch-react19.js
          cat package.json
      - name: Install dependencies
        run: npm install
      - name: Biome
        run: node --run biome:ci
      - name: Prettier
        run: node --run prettier:check
      - name: Build package
        run: |
          node --run build
          node --run build:types
      - name: Build website
        run: node --run build:website

  publish:
    needs: test # Only run if tests pass
    if: github.ref == 'refs/heads/port-changes' && matrix.react == 18 # Only publish for React 18
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm install

      - name: Build the package
        run: npm run build

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
